mysite/blog/urls.py
from django.urls import re_path
from . import views

app_name = 'blog'

urlpatterns = [
    re_path(r'^$', views.post_list, name='post_list'),
    # re_path(r'^$', views.PostListView.as_view(), name='post_list'),
    re_path(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
            views.post_detail, name='post_detail'),
    re_path(r'^tag/(?P<tag_slug>[-\w]+)/$',
            views.post_list, name="post_list_by_tag")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

mysite/blog/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    objects = models.Manager()
    published = PublishedManager()

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug
        ])

    class Meta:
        ordering = ('-publish', )

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommenctForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

mysite/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from taggit.models import Tag

from .utils import get_post_similar_posts
from .models import Post
from .forms import CommenctForm, EmailPostForm


def post_list(request, tag_slug=None):
    obj_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        obj_list = obj_list.filter(tags__in=[tag])

    paginator = Paginator(obj_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {
        'posts': posts,
        'page': page,
        'tag': tag
    })


def post_detail(request, year, month, day, post):
    post: Post = get_object_or_404(Post, slug=post, status='published',
                                   publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    similar_posts = get_post_similar_posts(post)
    new_comment = False
    if request.method == 'POST':
        comment_form = CommenctForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            new_comment = True
            return redirect(post.get_absolute_url())
    else:
        comment_form = CommenctForm()
    return render(request, 'blog/post/detail.html', {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'new_comment': new_comment,
        'similar_posts': similar_posts
    })


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    send = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) recommends you reading '{post.title}'"
            message = f"Read '{post.title}' at {post_url}\n\n{cd['name']}'s recomments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            send = True
            return redirect(post.get_absolute_url())
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'send': send})


from django.views.generic import ListView


class PostListView(ListView):
    queryset = Post.published.all()
    # query results, default is object_list if don't specify any context_object_name
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'  # default is blog/post_list.html
    # default page result is page_obj

mysite/blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
{% get_most_commented_posts 5 %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet"/>
</head>
<body>
    <div class="container">
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>

        <div class="sidebar">
            <h2>My Blog </h2>
            <p>This is my blog. </p>
            <p>I've written {% total_posts %} posts so far.</p>
            <h3>Latest posts</h3>
            {% show_latest_posts 3 %}
            <h3>Most commented posts</h3>
            <ul>
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    
</body>
</html>

mysite/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
    {{ post.title }}
{% endblock title %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <hr />
    <p>
        Tags: {{ post.tags.all|join:", " }}
    </p>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {% comment %} {{ post.body|linebreaks }} {% endcomment %}
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>
    <hr />
    <h2>Similary posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href='{{ post.get_absolute_url }}'>
                {{ post.title }}
            </a>
        </p>
    {% endfor %}

    
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p>
                「#{{ forloop.counter }}」 Comment by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {% comment %} {{ comment_form.as_p }} {% endcomment %}
            {% for field in comment_form %}
                <div>
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <br />
                    {{ field }}
                </div>
            {% endfor %}
            {% csrf_token %}
            <p>
                <input type="submit" value="Add comment"/>
            </p>
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock title %}
{% block content %}
    <h1>My Blog</h1>
    <hr />
    {% if tag %}
        <h2>
            Posts tagged with "{{ tag.name }}"
        </h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
                Tags: 
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {% comment %} {{ post.body|truncatewords:30|linebreaks }} {% endcomment %}
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% comment %} {% include "blog/pagination.html" with page=page_obj %} {% endcomment %}
    {% include "blog/pagination.html" with page=posts %}
{% endblock content %}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Share a post{% endblock title %}
{% block content %}
    {% if send %}
        <h1>E-mail successfully send</h1>
        <p>
            "{{ post.title }}" was successfully send to {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail </h1>
        <form action="." method="post">
            {% comment %} {{ form.as_p }} {% endcomment %}
            {% for field in form %}
                <div>
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <br />
                    {{ field }}
                </div>
            {% endfor %}
            {% csrf_token %}
            <input type="submit" value="send e-mail" />
        </form>
    {% endif %}
{% endblock content %}